tpplus:
  # 是否启用 -- 插件全局开关
  enable: true
  # 传送阵基石类型 1-铁块 2-钻石块 -- 其他值全部按默认铁块处理
  baseType: "1"
  # 传送需要消耗指定物品开关 默认关 -- 该功能还未开发 配置先放上来 避免后续更新还要改配置
  useKey: false
  # 传送需要消耗的物品类型 1-青金石 2-红石 -- 其他值全部按默认青金石处理 该功能还未开发 配置先放上来 避免后续更新还要改配置
  keyType: "1"